'use client';

import Sidebar from '@/components/Sidebar'
import './globals.css'
import { SessionProvider } from 'next-auth/react'

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}) {
  return (

    
    <html lang="en"  suppressHydrationWarning={true}>
       
      <body>
        <SessionProvider>

          {children}
        </SessionProvider>
          </body>
    
   
    </html>

   
  )
}
